saved_dir: /home/s/polyp/models

train_root_dir: /home/s/polyp/data/well_done/WLIv5_pub_640/Train/images/
train_txt_path:
  - /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_wo_non.txt
  - /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_w_non.txt
  - /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_w_non.txt
  - /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_w_non.txt
  - /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_w_non.txt
  - /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_w_non.txt
test_root_dir: /home/s/polyp/data/well_done/WLIv5_pub_640/Test/images/
test_txt_path: /home/s/polyp/neoplasm-segmentation/config/wliv5_noud/wliv5_noud_test.txt

# Color 
mask_values:
  polyp: [255, 255, 255]
  neoplastic: [255, 0, 0]
  non-neoplastic: [0, 255, 0]
  undefined: [255, 255, 0]

# Training size
height: 352
width: 352

# Training params
lr: 1e-3
min_lr: 0
batch_size: 4
num_epoch: 20
warmup_epoch: 5
weight_decay: 1e-4